CREATE TABLE CLINICS
(
    CLINIC_ID                  VARCHAR(50)  NOT NULL,
    NAME                       VARCHAR(255) NOT NULL,
    DOC_CNPJ                   VARCHAR(15)  NOT NULL,
    SOCIAL_NAME                VARCHAR(255) NOT NULL,
    FANTASY_NAME               VARCHAR(255) NOT NULL,
    EMAIL                      VARCHAR(320) NOT NULL,
    LEGAL_REPRESENTATIVE_ID    VARCHAR(15),
    LEGAL_REPRESENTATIVE_CPF   VARCHAR(15),
    LEGAL_REPRESENTATIVE_RG    VARCHAR(15),
    LEGAL_REPRESENTATIVE_NAME  VARCHAR(255),
    LEGAL_REPRESENTATIVE_PHONE VARCHAR(15),
    CEP                        VARCHAR(8),
    STREET_NAME                VARCHAR(100),
    NEIGHBORHOOD               VARCHAR(100),
    CITY                       VARCHAR(100),
    STATE                      VARCHAR(50),
    COMPLEMENT                 VARCHAR(100),
    STATUS                     BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (CLINIC_ID)
)

CREATE TABLE CLIENTS (
    CLINIC_ID       VARCHAR(50)     NOT NULL,
    CLIENT_ID       VARCHAR(50)     NOT NULL,
    NAME            VARCHAR(255)    NOT NULL,
    BIRTHDAY        DATETIME,
    DOC_CPF         VARCHAR(15),
    DOC_RG          VARCHAR(15),
    EMAIL           VARCHAR(320),
    PHONE           VARCHAR(15),
    CELLPHONE       VARCHAR(15),
    EMERGENCY_NAME  VARCHAR(255),
    EMERGENCY_PHONE VARCHAR(15),
    OCCUPATION      VARCHAR(50),
    CEP             VARCHAR(8),
    STREET_NAME     VARCHAR(100),
    NEIGHBORHOOD    VARCHAR(100),
    CITY            VARCHAR(100),
    STATE           VARCHAR(50),
    COMPLEMENT      VARCHAR(100),
    LEGAL_REPRESENTATIVE_CPF    VARCHAR(15),
    LEGAL_REPRESENTATIVE_RG     VARCHAR(15),
    LEGAL_REPRESENTATIVE_NAME   VARCHAR(255),
    LEGAL_REPRESENTATIVE_PHONE  VARCHAR(15),
    LEGAL_REPRESENTATIVE_TYPE   VARCHAR(50),
    STATUS                      BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (CLINIC_ID, CLIENT_ID),
    FOREIGN KEY (CLINIC_ID) REFERENCES CLINICS(CLINIC_ID)
);

CREATE TABLE PROCEEDINGS
(
    PROCEEDING_ID       VARCHAR(50)     NOT NULL,
    NAME                VARCHAR(255)    NOT NULL,
    STATUS              BOOLEAN DEFAULT TRUE
);

CREATE TABLE CLINIC_PROCEEDINGS
(
    CLINIC_ID       VARCHAR(50)     NOT NULL,
    PROCEEDING_ID   VARCHAR(50)     NOT NULL,
    VALUE           DECIMAL(16,8)   ,
    TIME            INTEGER         ,
    HAS_RETURN      BOOLEAN         ,
    DAYS_TO_RETURN  INTEGER         ,
    PRIMARY KEY (CLINIC_ID, PROCEEDING_ID),
    FOREIGN KEY (CLINIC_ID) REFERENCES CLINICS(CLINIC_ID),
    FOREIGN KEY (PROCEEDING_ID) REFERENCES PROCEEDINGS(PROCEEDING_ID)
);

CREATE TABLE CLINIC_TREATMENT_PLANS
(
    CLINIC_ID       VARCHAR(50)     NOT NULL,
    CLIENT_ID       VARCHAR(50)     NOT NULL,
    TREATMENT_ID    VARCHAR(50)     NOT NULL,
    DISCOUNT        DECIMAL(16,8)   NOT NULL,
    TOTAL_PRICE     DECIMAL(16,8)   NOT NULL,
    COMPLAINT       VARCHAR(65535),
    COMMENTS        VARCHAR(65535),
    STATUS          VARCHAR(15),
    PRIMARY KEY (CLINIC_ID, CLIENT_ID, TREATMENT_ID),
    FOREIGN KEY (CLINIC_ID) REFERENCES CLINICS(CLINIC_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);

CREATE TABLE CLINIC_TREATMENT_PLANS_STATUS
(
    STATUS  VARCHAR(15),
    NAME    VARCHAR(50)
);

INSERT CLINIC_TREATMENT_PLANS_STATUS VALUES ('CREATED', 'INICIADO');
INSERT CLINIC_TREATMENT_PLANS_STATUS VALUES ('WAITING', 'AGUARDANDO APROVAÇÃO');
INSERT CLINIC_TREATMENT_PLANS_STATUS VALUES ('APPROVED', 'APROVADO');
INSERT CLINIC_TREATMENT_PLANS_STATUS VALUES ('IN-PROGRESS', 'EM ANDAMENTO');
INSERT CLINIC_TREATMENT_PLANS_STATUS VALUES ('CANCELED', 'CANCELADO');
INSERT CLINIC_TREATMENT_PLANS_STATUS VALUES ('COMPLETED', 'FINALIZADO');

CREATE TABLE CLINIC_TREATMENT_PLAN_PROCEEDINGS
(
    CLINIC_ID           VARCHAR(50)     NOT NULL,
    CLIENT_ID           VARCHAR(50)     NOT NULL,
    TREATMENT_ID        VARCHAR(50)     NOT NULL,
    PROCEEDING_ORDER    VARCHAR(50)     NOT NULL,
    PROCEEDING_ID       VARCHAR(50)     NOT NULL,
    IS_ACCEPTED     BOOLEAN NOT NULL DEFAULT FALSE,
    QUANTITY        INTEGER NOT NULL DEFAULT 1,
    DATE            DATETIME,
    PRIMARY KEY (CLINIC_ID, CLIENT_ID, TREATMENT_ID, PROCEEDING_ID),
    FOREIGN KEY (CLINIC_ID) REFERENCES CLINICS(CLINIC_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (TREATMENT_ID) REFERENCES CLINIC_TREATMENT_PLANS(TREATMENT_ID),
    FOREIGN KEY (PROCEEDING_ID) REFERENCES CLINIC_PROCEEDINGS(PROCEEDING_ID)
);

CREATE TABLE CLINIC_TREATMENT_PLAN_ANAMNESIS
(
    CLINIC_ID                   VARCHAR(50)     NOT NULL,
    CLIENT_ID                   VARCHAR(50)     NOT NULL,
    TREATMENT_ID                VARCHAR(50)     NOT NULL,
    ACCEPT_WHATSAPP_CONTACT     BOOLEAN         NOT NULL DEFAULT FALSE,
    MOTIVATION                  VARCHAR(65535)  ,
    HAS_ANOTHER_TREATMENT       BOOLEAN         NOT NULL DEFAULT FALSE,
    TREATMENT                   VARCHAR(65535)  ,
    HAS_BOTULINUM_TOXIN         BOOLEAN         NOT NULL DEFAULT FALSE,
    BOTULINUM_TOXIN_REGION      VARCHAR(65535)  ,
    BOTULINUM_TOXIN_DATE        DATETIME        ,
    BOTULINUM_TOXIN_QTY         INTEGER         ,
    BOTULINUM_TOXIN_APPLICATION VARCHAR(65535)  ,
    BOTULINUM_TOXIN_AFTER       VARCHAR(65535)  ,
    HAS_FOOD_ALLERGY            BOOLEAN         NOT NULL DEFAULT FALSE,
    FOOD_ALLERGY                VARCHAR(65535)  ,
    HAS_MEDICATION              BOOLEAN         NOT NULL DEFAULT FALSE,
    MEDICATION                  VARCHAR(65535)
);

CREATE TABLE CLINIC_TREATMENT_PLAN_PROCEEDING_CONTRACTS
(
    CLINIC_ID           VARCHAR(50)     NOT NULL,
    CLIENT_ID           VARCHAR(50)     NOT NULL,
    TREATMENT_ID        VARCHAR(50)     NOT NULL,
    PROCEEDING_ID       VARCHAR(50)     NOT NULL,
    IP                  VARCHAR(50),
    USER_AGENT          VARCHAR(65535),
    LATITUDE            DECIMAL(16,8),
    LONGITUDE           DECIMAL(16,8),
    ACCURACY            DECIMAL(16,8),
    PRIMARY KEY (CLINIC_ID, CLIENT_ID, TREATMENT_ID, PROCEEDING_ID),
    FOREIGN KEY (CLINIC_ID) REFERENCES CLINICS(CLINIC_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (TREATMENT_ID) REFERENCES CLINIC_TREATMENT_PLANS(TREATMENT_ID),
    FOREIGN KEY (PROCEEDING_ID) REFERENCES CLINIC_PROCEEDINGS(PROCEEDING_ID)
);
